[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["global-telemetry-system"]
force_sort_within_sections = true
combine_as_imports = true
include_trailing_comma = true
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
strict_optional = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
